CREATE SCHEMA IF NOT EXISTS mybatis_demo; USE mybatis_demo ;
CREATE TABLE  artist (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(200) NOT NULL, PRIMARY KEY (id)) ENGINE = InnoDB;
CREATE TABLE painting (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(200) NOT NULL, artist_id INT NOT NULL, PRIMARY KEY (id)) ENGINE = InnoDB;
ALTER TABLE painting ADD FOREIGN KEY (artist_id) REFERENCES artist (id) ON DELETE CASCADE;